version: '3.8'

services:
  db:
    image: influxdb
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    env_file:
      - .env
  spot:
    image: spot
    build:
      context: ./services/spot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db


    